### ISSUE TITLE
utf8 conversion

### ISSUE THREAD

**Issue by clombion** [hay/xml2json#45]
The script worked great for me from XML to Json, but it was unable to process correctly words like "Président" which became "Pr\u00e9sident". Is it possible to fix this?

**Comment by sati-bodhi** [comment]
Same issue here. Chinese utf8 characters get parsed into unicode numbers. \u738b\u696d

**Comment by goojayfan** [comment]
I meet the same problem.
```
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python35\Scripts\xml2json-script.py", line 11, in <module>
    load_entry_point('xml2json==0.1', 'console_scripts', 'xml2json')()
  File "c:\users\admin\appdata\local\programs\python\python35\lib\site-packages\xml2json.py", line 226, in main
    input = inputstream.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbc in position 1667520: illegal multibyte sequence
```
